complexity:
  LongParameterList:
    functionThreshold: 5
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignoreAnnotatedFunctions: ['Preview', 'PreviewLightDark']

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

style:
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview', 'PreviewLightDark']
  MaxLineLength:
    maxLineLength: 140
