name: TESTING-RELEASE

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 0'
env:
  JAVA_VERSION: 17
  UPLOAD_KEY_STORE_PATH: ${{ github.workspace }}/upload_keystore.jks
  SIGNING_KEY_STORE_PATH: ${{ github.workspace }}/signing_keystore.jks
  SERVICE_ACCOUNT_JSON_PATH: ${{ github.workspace }}/service_account.json
jobs:
  semantic-release:
    name: Semantic release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Get current version name
        run: |
          CURRENT_VERSION_NAME=$(grep "versionName" build.properties | cut -d'=' -f2)
          echo "current_version_name=${CURRENT_VERSION_NAME}" >> "$GITHUB_ENV"

      - name: Generate new version name using semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          fromTag: v${{ env.current_version_name }}
          noNewCommitBehavior: "silent"
          noVersionBumpBehavior: "patch"

      - name: Write version name, version code and tag name to env
        run: |
          SEMANTIC_VERSION=${{ steps.semver.outputs.next }}
          VERSION_NAME=${SEMANTIC_VERSION#v}
          VERSION_CODE=$(date +"%y%V%u42")
          TAG_NAME="v${VERSION_NAME}"
          echo "version_name=${VERSION_NAME}" >> "$GITHUB_ENV"
          echo "version_code=${VERSION_CODE}" >> "$GITHUB_ENV"
          echo "tag_name=${TAG_NAME}" >> "$GITHUB_ENV"    

      - name: Write version name and version code to build.properties
        run: |
          sed -i -e "
            s/versionName=.*/versionName=$version_name/
            s/versionCode=.*/versionCode=$version_code/
          " build.properties   

      - name: Add tag to repository
        run: |
          git tag $tag_name
          git push origin $tag_name

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: v${{ env.current_version_name }}
          toTag: ${{ env.tag_name }}
          excludeTypes: build,docs,other,style,ci,chore

      - name: Print Changelog
        run: |
          echo "${{ steps.changelog.outputs.changelog }}"
          cat CHANGELOG.md
        
      - name: Commit changes
        run: |
          git config --global user.email "release-bot@musikus.app"
          git config --global user.name "Release Bot"
          git commit -am "chore: bump version to ${{ env.version_name }}"
          git push origin HEAD:main
        shell: bash

  github-release:
    name: Release apk to Github
    needs: semantic-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Get version name, code and tag
        run: |
          VERSION_NAME=$(grep "versionName" build.properties | cut -d'=' -f2)
          VERSION_CODE=$(grep "versionCode" build.properties | cut -d'=' -f2)
          echo "version_name=${VERSION_NAME}" >> "$GITHUB_ENV"
          echo "version_code=${VERSION_CODE}" >> "$GITHUB_ENV"
          echo "tag_name=v${VERSION_NAME}" >> "$GITHUB_ENV"

      - name: Write commit hash to build.properties
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s/commitHash=.*/commitHash=$COMMIT_HASH/" build.properties

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: gradle

      - name: Decode keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: ${{ env.SIGNING_KEY_STORE_PATH }}
        run: |
          echo $ENCODED_STRING | base64 --decode > $SIGNING_KEY_STORE_PATH

      - name: Build apk
        env:
          SIGNING_KEY_STORE_PATH: ${{ env.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          ./gradlew assembleRelease

      - name: Release apk on Github
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: ${{ env.tag_name }}
          files: |
            app/build/outputs/apk/release/*.apk

  play-release:
    name: Release bundle to Google Play
    needs: semantic-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Get version name, code and tag
        run: |
          VERSION_NAME=$(grep "versionName" build.properties | cut -d'=' -f2)
          VERSION_CODE=$(grep "versionCode" build.properties | cut -d'=' -f2)
          echo "version_name=${VERSION_NAME}" >> "$GITHUB_ENV"
          echo "version_code=${VERSION_CODE}" >> "$GITHUB_ENV"
          echo "tag_name=v${VERSION_NAME}" >> "$GITHUB_ENV"

      - name: Write commit hash to build.properties
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s/commitHash=.*/commitHash=$COMMIT_HASH/" build.properties

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: gradle

      - name: Decode keystore
        env:
          ENCODED_STRING: ${{ secrets.UPLOAD_KEY_STORE_BASE64 }}
          UPLOAD_KEY_STORE_PATH: ${{ env.UPLOAD_KEY_STORE_PATH }}
        run: |
          echo $ENCODED_STRING | base64 --decode > $UPLOAD_KEY_STORE_PATH

      - name: Decode service account json
        env:
          ENCODED_STRING: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          echo $ENCODED_STRING | base64 --decode > $SERVICE_ACCOUNT_JSON_PATH

      - name: Build release apk and bundle
        env:
          SIGNING_KEY_STORE_PATH: ${{ env.UPLOAD_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.UPLOAD_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.UPLOAD_STORE_PASSWORD }}
        run: |
          ./gradlew bundleRelease
          ./gradlew assembleRelease

#      - name: Signing report
#        if: env.skip_release == 'false'
#        run: ./gradlew signingReport

      - name: Upload bundle to the Google Play Console alpha track
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: app.musikus
          serviceAccountJson: ${{ env.SERVICE_ACCOUNT_JSON_PATH }}
          releaseFiles: app/build/outputs/bundle/release/*.aab
          releaseName: ${{ env.version_name }}
          track: alpha
          status: draft
