name: TESTING-RELEASE

on:
  workflow_dispatch
jobs:
  release:
    name: Release to play console closed testing track
    runs-on: ubuntu-latest

    steps:
      - name: Hello there
        run: echo General Kenobi
